name: Generate Tokyo Night Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup directories
        run: mkdir -p dist

      - name: Generate Light Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_file: dist/snake-light.svg
          color_bg: "1a1b27"  # Tokyo Night base
          color_fg: "414868,7aa2f7,bb9af7,9ece6a,e0af68"  # Tokyo Night palette
          color_line: "1a1b27"  # Grid line color

      - name: Generate Dark Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_file: dist/snake-dark.svg
          dark_mode: true
          color_bg: "1a1b27"
          color_fg: "414868,7aa2f7,bb9af7,9ece6a,e0af68"
          color_line: "1a1b27"

      - name: Verify files
        run: |
          ls -la dist/
          echo "File verification complete"

      - name: Publish Snakes
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
