name: Tokyo Night Snake Generator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Snakes
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: |
            --output dist/snake.svg \
            --color-bg d5d6db \
            --color-fg 414868,7aa2f7,bb9af7,9ece6a,e0af68 \
            --color-line d5d6db \
            --dark-mode-output dist/snake-dark.svg \
            --dark-color-bg 1a1b27 \
            --dark-color-fg a9b1d6,7aa2f7,bb9af7,9ece6a,e0af68 \
            --dark-color-line 1a1b27

      - name: Force Create Files
        run: |
          [ -f dist/snake.svg ] || echo "Empty" > dist/snake.svg
          [ -f dist/snake-dark.svg ] || echo "Empty" > dist/snake-dark.svg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
          allow_empty: true
