name: Generate Contribution Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Light-mode Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          mode: light
          palette: "1a1b27,70a5fd,7aa2f7,c0caf5,a9b1d6"
          output: dist/snake-light.svg

      - name: Generate Dark-mode Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          mode: dark
          palette: "1a1b27,70a5fd,7aa2f7,c0caf5,a9b1d6"
          output: dist/snake-dark.svg

      # ── Post-process both SVGs to recolor the grid squares ──
      - name: Apply Tokyo Night grid background
        run: |
          BG="#1a1b27"    # Tokyo Night background
          for f in dist/snake-*.svg; do
            # replace any fill="#ebedf0" (light-mode grid) or fill="#161b22" (dark-mode grid)
            sed -i "s/fill=\"#ebedf0\"/fill=\"${BG}\"/g" "$f"
            sed -i "s/fill=\"#161b22\"/fill=\"${BG}\"/g" "$f"
          done

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

