name: Tokyo Night Snake Generator

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main  # Add push trigger for testing

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup directories
        run: mkdir -p dist

      - name: Generate Light Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: >-
            --output dist/snake.svg
            --color-bg d5d6db
            --color-fg 414868,7aa2f7,bb9af7,9ece6a,e0af68
            --color-line d5d6db

      - name: Generate Dark Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: >-
            --output dist/snake-dark.svg 
            --color-bg 1a1b27
            --color-fg a9b1d6,7aa2f7,bb9af7,9ece6a,e0af68
            --color-line 1a1b27
            --dark-mode

      - name: Verify SVG generation
        run: |
          if [ ! -f dist/snake.svg ]; then
            echo "::error::Light snake file not generated!"
            exit 1
          fi
          if [ ! -f dist/snake-dark.svg ]; then
            echo "::error::Dark snake file not generated!"
            exit 1
          fi
          ls -la dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
