name: Tokyo Night Snake Generator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup directories
        run: mkdir -p dist

      - name: Generate Light Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: >-
            --output dist/snake.svg
            --color-bg d5d6db
            --color-fg 414868,7aa2f7,bb9af7,9ece6a,e0af68
            --color-line d5d6db
            --no-progress

      - name: Check Light SVG
        run: |
          if [ ! -f dist/snake.svg ]; then
            echo "ERROR: dist/snake.svg was not created!"
            echo "Creating minimal fallback so deploy can proceed."
            cat <<EOF > dist/snake.svg
            <svg xmlns="http://www.w3.org/2000/svg" width="1" height="1"></svg>
            EOF
          fi

      - name: Generate Dark Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: >-
            --output dist/snake-dark.svg
            --color-bg 1a1b27
            --color-fg a9b1d6,7aa2f7,bb9af7,9ece6a,e0af68
            --color-line 1a1b27
            --dark-mode
            --no-progress

      - name: Check Dark SVG
        run: |
          if [ ! -f dist/snake-dark.svg ]; then
            echo "ERROR: dist/snake-dark.svg was not created!"
            echo "Creating minimal fallback so deploy can proceed."
            cat <<EOF > dist/snake-dark.svg
            <svg xmlns="http://www.w3.org/2000/svg" width="1" height="1"></svg>
            EOF
          fi

      - name: Debug dist directory
        run: |
          echo "==== dist contents ===="
          ls -alh dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
          allow_empty: true
