name: Tokyo Night Snake Generator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify Contributions Data
        run: |
          echo "Checking contribution visibility..."
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/users/${{ github.repository_owner }}/events/public" \
          | jq '.[].type' | uniq -c

      - name: Setup Python (snk dependency)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate Snakes with Fallback
        uses: Platane/snk@v3
        id: snake-gen
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: >-
            --output dist/snake.svg
            --color-bg d5d6db
            --color-fg 414868,7aa2f7,bb9af7,9ece6a,e0af68
            --color-line d5d6db
            --dark-mode-output dist/snake-dark.svg
            --dark-color-bg 1a1b27
            --dark-color-fg a9b1d6,7aa2f7,bb9af7,9ece6a,e0af68
            --dark-color-line 1a1b27
            --show-activity
            --force-week 1

      - name: Validate Output
        run: |
          echo "Current directory: $(pwd)"
          ls -la dist/
          
          if [ ! -f dist/snake.svg ]; then
            echo "Using fallback snake..."
            wget -O dist/snake.svg https://raw.githubusercontent.com/Platane/snk/output/snake.svg
            wget -O dist/snake-dark.svg https://raw.githubusercontent.com/Platane/snk/output/snake-dark.svg
          fi

          echo "File contents:"
          head -n 2 dist/snake.svg
          echo "File type:"
          file dist/snake.svg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
          allow_empty: false
