name: Generate Contribution Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Light-mode Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          args: "--github-user-name ${{ github.repository_owner }} --output-file dist/snake-light.svg --color-bg 1a1b27 --color-fg 414868,7aa2f7,bb9af7,9ece6a,e0af68"

      - name: Generate Dark-mode Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          args: "--github-user-name ${{ github.repository_owner }} --output-file dist/snake-dark.svg --color-bg 1a1b27 --color-fg 414868,7aa2f7,bb9af7,9ece6a,e0af68 --dark-mode"

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
