name: Generate Contribution Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p dist

      - name: Generate Light-mode Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          output_file: dist/snake-light.svg
          color_bg: "1a1b27"  # Tokyo Night background
          color_fg: "414868,7aa2f7,bb9af7,9ece6a,e0af68"  # Tokyo Night accent colors

      - name: Generate Dark-mode Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          output_file: dist/snake-dark.svg
          dark_mode: true
          color_bg: "1a1b27"  # Same background
          color_fg: "414868,7aa2f7,bb9af7,9ece6a,e0af68"  # Same accents

      - name: Fix grid background colors
        run: |
          # Fixes for grid lines that might use default colors
          for f in dist/snake-*.svg; do
            sed -i 's/fill="#ebedf0"/fill="#1a1b27"/g' "$f"  # Light mode grid
            sed -i 's/fill="#161b22"/fill="#1a1b27"/g' "$f"  # Dark mode grid
          done

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
