name: Tokyo Night Snake Generator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup directories
        run: mkdir -p dist

      - name: Generate Snake Locally with Docker
        run: |
          docker run --rm -v $(pwd)/dist:/output platane/snk:v3 \
            --github_user_name=${{ github.repository_owner }} \
            --output=/output/snake.svg \
            --color-bg=d5d6db \
            --color-fg=414868,7aa2f7,bb9af7,9ece6a,e0af68 \
            --color-line=d5d6db \
            --no-progress

      - name: Verify Generated File
        run: |
          if [ -f dist/snake.svg ]; then
            echo "SVG file was generated successfully!"
          else
            echo "ERROR: snake.svg was not found after generation."
            exit 1
          fi

      - name: Debug File Content
        run: |
          if [ -f dist/snake.svg ]; then
            echo "Contents of dist/snake.svg:"
            cat dist/snake.svg
          else
            echo "ERROR: dist/snake.svg not created"
          fi

      - name: Commit and Push Generated Snake
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/snake.svg
          git commit -m "Update GitHub commit snake visualization"
          git push
