name: Generate Contribution Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Light-mode Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_file: dist/snake-light.svg
          color_bg: "1a1b27"
          color_fg: "414868,7aa2f7,bb9af7,9ece6a,e0af68"

      - name: Generate Dark-mode Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_file: dist/snake-dark.svg
          dark_mode: true
          color_bg: "1a1b27"
          color_fg: "414868,7aa2f7,bb9af7,9ece6a,e0af68"

      - name: Fix grid background
        run: |
          # Wait briefly to ensure files are written
          sleep 1
          # Apply Tokyo Night background to grid
          for f in dist/snake-*.svg; do
            [ -f "$f" ] || continue  # Handle case where no files match
            sed -i 's/fill="%23ebedf0"/fill="%231a1b27"/g' "$f"  # URL-encoded colors
            sed -i 's/fill="%23161b22"/fill="%231a1b27"/g' "$f"
          done

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
