name: Tokyo Night Snake Generator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup directories
        run: mkdir -p dist

      - name: Debug Before Generation
        run: |
          echo "Working directory before generation:"
          pwd
          echo "Contents of working directory before generation:"
          ls -R
          echo "Contents of dist directory before generation:"
          ls -R dist || echo "dist directory not found"

      - name: Generate Light Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: >-
            --color-bg d5d6db
            --color-fg 414868,7aa2f7,bb9af7,9ece6a,e0af68
            --color-line d5d6db
            --no-progress
            dist/snake.svg

      - name: Verify Generated File
        run: |
          if [ -f dist/snake.svg ]; then
            echo "SVG file was generated successfully!"
          else
            echo "ERROR: snake.svg was not found after generation."
            exit 1
          fi

      - name: Debug After Generation
        run: |
          echo "Working directory after generation:"
          pwd
          echo "Contents of working directory after generation:"
          ls -R
          echo "Contents of dist directory after generation:"
          ls -R dist || echo "dist directory not found"

      - name: Debug File Content
        run: |
          if [ -f dist/snake.svg ]; then
            echo "Contents of dist/snake.svg:"
            cat dist/snake.svg
          else
            echo "ERROR: dist/snake.svg not created"
          fi

      - name: Ensure Fallback SVG
        run: |
          if [ ! -f dist/snake.svg ]; then
            echo "Creating fallback snake.svg"
            echo '<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"/>' > dist/snake.svg
          fi

      - name: List dist contents
        run: ls -alh dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
          allow_empty: true
