name: Tokyo Night Snake Generator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          mkdir -p dist
          echo "Workspace: $PWD"
          echo "Directory structure:"
          tree -a

      - name: Generate Light Snake (Debug)
        uses: Platane/snk@v3
        id: snake-light
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: >-
            --output ${{ github.workspace }}/dist/snake.svg
            --color-bg d5d6db
            --color-fg 414868,7aa2f7,bb9af7,9ece6a,e0af68
            --color-line d5d6db
            --show-activity

      - name: Verify Light Snake
        run: |
          echo "Current directory: $PWD"
          ls -la dist/
          if [ -f dist/snake.svg ]; then
            echo "Snake generated successfully!"
            echo "File info:"
            file dist/snake.svg
            echo "First 50 chars:"
            head -c 50 dist/snake.svg
          else
            echo "::error::Light snake generation failed!"
            exit 1
          fi

      - name: Generate Dark Snake (Debug)
        uses: Platane/snk@v3
        id: snake-dark
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: >-
            --output ${{ github.workspace }}/dist/snake-dark.svg
            --color-bg 1a1b27
            --color-fg a9b1d6,7aa2f7,bb9af7,9ece6a,e0af68
            --color-line 1a1b27
            --dark-mode
            --show-activity

      - name: Verify Dark Snake
        run: |
          ls -la dist/
          if [ -f dist/snake-dark.svg ]; then
            echo "Dark snake generated successfully!"
            echo "File info:"
            file dist/snake-dark.svg
            echo "First 50 chars:"
            head -c 50 dist/snake-dark.svg
          else
            echo "::error::Dark snake generation failed!"
            exit 1
          fi

      - name: Deploy with Verification
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
          allow_empty: false
        env:
          DEBUG: true
