name: Generate Contribution Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Light-mode Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          mode: light
          palette: "1a1b27,70a5fd,7aa2f7,c0caf5,a9b1d6"
          output: dist/github-contribution-grid-snake.svg

      - name: Generate Dark-mode Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          mode: dark
          palette: "1a1b27,70a5fd,7aa2f7,c0caf5,a9b1d6"
          output: dist/github-contribution-grid-snake-dark.svg

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
